### ISSUE TITLE
auto resize prompt input field in image page

### ISSUE THREAD

**Issue by ShreyTanna29** [ShreyTanna29/curious.AI#52]
**Is your feature request related to a problem? Please describe.**
when prompt gets big in image page, input box shows an scroll bar which looks ugly

**Describe the solution you'd like**
auto resize the textarea, so that the scrollbar doesnt appear.

**Describe alternatives you've considered**
N/A

**Check if applicable**
- [x] I have checked that this feature request does not exists on issues page.

**Additional context**

![Screenshot from 2024-12-06 13-38-10](https://github.com/user-attachments/assets/50944792-bba7-4b5f-960a-fa2ff70cf502)

**Comment by dsawebappayush** [comment]
Hi @ShreyTanna29 is this issue still open? 
If yes,
I would like to contribute to this bug

**Comment by ShreyTanna29** [comment]
> Hi @ShreyTanna29 is this issue still open? If yes, I would like to contribute to this bug

@dsawebappayush sure, go ahead.

**Comment by dsawebappayush** [comment]
hey @ShreyTanna29  i am getting following error while running the app
Error: @clerk/nextjs: Missing publishableKey. You can get your key at https://dashboard.clerk.com/last-active?path=api-keys.
I am using clerk first time can you clear with me if this is suppose to happen

**Comment by ShreyTanna29** [comment]
@dsawebappayush  you will need clerk publishable and secret key, go to clerk website, create an account and then create a new app/project and get your both the keys and paste it in the .env file. plus you will need all the keys specified in .env.example, all keys are free and easy to get. copy .env.example and rename it to .env and replace the values with your keys in that .env. let me know if you need any further help.

**Comment by dsawebappayush** [comment]
@ShreyTanna29  I am getting the following error.

Error: Clerk: Handshake token verification failed: Unable to find a signing key in JWKS that matches the kid='ins_2mZ7HiqQuHl1H0SKg21fniEEC5D' of the provided session token. Please make sure that the __session cookie or the HTTP authorization header contain a Clerk-generated session JWT. The following kid is available: ins_2qGSSNXVHzj03itOhIOB66INUX9 Go to your Dashboard and validate your secret and public keys are correct. Contact support@clerk.com if the issue persists. (reason=jwk-kid-mismatch, token-carrier=undefined).
    at handleHandshakeTokenVerificationErrorInDevelopment (webpack-internal:///(middleware)/./node_modules/@clerk/backend/dist/chunk-HGGLOBDA.mjs:2549:11)
    at authenticateRequestWithTokenInCookie (webpack-internal:///(middleware)/./node_modules/@clerk/backend/dist/chunk-HGGLOBDA.mjs:2561:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async eval (webpack-internal:///(middleware)/./node_modules/@clerk/nextjs/dist/esm/server/clerkMiddleware.js:75:28)
    at async eval (webpack-internal:///(middleware)/./node_modules/next/dist/build/webpack/loaders/next-middleware-loader.js?absolutePagePath=C%3A%5CUsers%5CLENOVO%5Ccurious.AI%5Cmiddleware.ts&page=%2Fmiddleware&rootDir=C%3A%5CUsers%5CLENOVO%5Ccurious.AI&matchers=&preferredRegion=&middlewareConfig=e30%3D!:26:20)
    at async eval (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:237:28)
    at async adapter (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/adapter.js:188:16)
    at async (file://C:\Users\LENOVO\curious.AI\node_modules\next\dist\server\web\sandbox\sandbox.js:122:26)
    at async runWithTaggedErrors (file://C:\Users\LENOVO\curious.AI\node_modules\next\dist\server\web\sandbox\sandbox.js:119:9)
    at async DevServer.runMiddleware (file://C:\Users\LENOVO\curious.AI\node_modules\next\dist\server\next-server.js:994:24)

**Comment by ShreyTanna29** [comment]
@dsawebappayush this error generally occurs when clerk's session token verification fails, this can be due to 2 reasons,

1. secret token in your .env does not match with clerk's app, make sure you have copied your both publishable and secret token correctly from clerk's website.
2. maybe your names of the variables in .env mismatch. check the below screenshot and make sure your variables in .env look something like this. obviously your keys would be different from this screen shot and dont use this as this keys are fake, just focus on syntax and naming.
![Screenshot from 2024-12-16 14-43-58](https://github.com/user-attachments/assets/528f911a-d56e-489f-9b1a-606562eef9be)


make sure the names of variable are exactly same, no smallcase and no space.

also make sure you have this as well, this is not related to your error, but is important for the auth to work properly.

![Screenshot from 2024-12-16 14-44-15](https://github.com/user-attachments/assets/730462b0-f9cb-43b8-9ee2-416c25d60d47)

let me know if this works or not.
